### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by thequbit** [craighaywood/VHDLObfuscate#1]
First, I am not a lawyer, and this is not legal advice.

There is no license for this repo and the code inside of it.  Might I suggest the General Public License v3, as it is a copy-left license and ensures that any changes that are made to your code in the future are released back to you and the community.

A copy of the license can be found [here](http://www.gnu.org/licenses/gpl-3.0.txt).  I am more than happy to submit a PR with the license in it, if you would like.

**Comment by craighaywood** [comment]
Thanks for the input, I have licensed the module under GPLv3

**Comment by thequbit** [comment]
:+1: Awesome!
